### ISSUE TITLE
upload-api should upgrade to `@ucanto/transport` that has more verbose error messages from HTTP transport non-ok responses

### ISSUE THREAD

**Issue by gobengo** [w3s-project/w3infra#336]
Goal:
* if/when this is released, w3infra should depend on it https://github.com/web3-storage/ucanto/pull/343
  * to get https://github.com/web3-storage/ucanto/commit/d5f6916a41447bcc32bfbd9378da2b4779ca2136

Why?
* this will make errors in w3up that come from w3infra (really any database-interaction failures) be easier to differentiate by error message, e.g. in tools like sentry. It should help us find errors faster, understand the cause, and prevent them from happening again.
  * e.g. having the connection url href in here will group all these http errors by the URL of the service that responded with non-ok

```[tasklist]
### Tasks
- [ ] https://github.com/web3-storage/ucanto/pull/343
- [x] PR bumping dep in w3up https://github.com/web3-storage/w3up/pull/1312
- [ ] PR bumping deps in w3infra
- [ ] release w3infra to prod after PR merge
```
